name: first workflow
on: push
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
    - name: get code
      uses: actions/checkout@v4
    - name: install nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: install dependencies
      run: npm ci
    # - name: Run react
    #   run: npm start
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: get code
      uses: actions/checkout@v4
    - name: install nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: install dependencies
      run: npm ci
    -name: Build project
      run: npm run build
    -name: deploy
      run: echo "deploying ..."
