name: Docker Build and Run

on:
  push:
    branches: [skip ci] 

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Run Docker container
        id: run_container
        run: |
          CONTAINER_ID=$(docker run -d -p 8080:3000 my-app)
          echo "Container ID: $CONTAINER_ID"
          echo "::set-output name=container_id::$CONTAINER_ID"

      - name: Display Docker container logs
        run: docker logs -f ${{ steps.run_container.outputs.container_id }}
